blueprint:
  name: Advanced Motion Activated Light
  description: Turns light on when motion detected, then off after motion clears & optional wait period. Includes time of day disabling.
  domain: automation
  input:
    light_entity:
      name: Light/Switch
      description: Select the light or switch to control.
      selector:
        entity:
          domain: 
            - light
            - switch
          multiple: true
    motion_sensor:
      name: Motion Sensor
      description: Select the motion sensor to monitor.
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
    wait_period:
      name: Wait Period
      description: Time in seconds to wait after motion stops before turning off the light.
      default: 360
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    active_time_start:
      name: Active Time Start
      description: Optional time range during which the automation is active.
      selector:
        entity:
    active_time_end:
      name: Active Time End
      description: Optional time range during which the automation is active.
      selector:
        time:

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: 'on'

variables:
  light_entity: !input light_entity
  wait_period: !input wait_period

condition:
  - condition: time
    after: !input active_time_start
    before: !input active_time_end

action:
  - service: light.turn_on
    target:
      entity_id: "{{ light_entity }}"
  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_sensor
        to: 'off'
  - delay: !input wait_period
  - service: light.turn_off
    target:
      entity_id: "{{ light_entity }}"
